apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes hetzner-helsinki in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success hetzner-helsinki
           disable denial hetzner-helsinki
        }
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-21T19:26:55Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "252"
  uid: e71b83b5-337d-41b3-986b-c8e2a2e3b5ca
